<form method="POST">
    <?php
        echo $_SESSION['error'] ?? '';
        echo $_SESSION['success'] ?? '';
        unset($_SESSION['error'], $_SESSION['success']);
    ?>
    <input type="text" name="title" value="<?php echo $this->todo['title']?>" style="font-size: 2rem" autofocus>
    <button style="font-size: 2rem; color: grey">Save changes</button>
    <br>
    <input type="radio" name="status" value="Pending" <?php echo ($this->todo['status'] === 'Pending') ? 'checked' : null; ?> >
    <label for="Pending">Pending</label>
    <input type="radio" name="status" value="In Process" <?php echo ($this->todo['status'] === 'In Process') ? 'checked' : null; ?>>
    <label for="In Process">In Process</label>
    <input type="radio" name="status" value="Completed" <?php echo ($this->todo['status'] === 'Completed') ? 'checked' : null; ?>>
    <label for="Completed">Completed</label>
</form>

<?php
    // REVIEW
    var_dump($this->todo);

?>