<?php $this->appendScript('intlCheck.js'); ?>

<?php
echo $_SESSION['error'] ?? '';
unset($_SESSION['error']);

$reqFrom = $_SERVER['REQUEST_URI'] ?? '';
$reqFrom = preg_match('/\/todo\/list/', $reqFrom);
$moreThanFive = count($this->userTodos) > 5 && !$reqFrom;
?>

<?php if (count($this->userTodos ?? [])) { ?>
    <?php echo (!$reqFrom) ? "<br>" : 
    '<div class="relative text-center vsm:w-full sm:w-fit">'; ?>
    <?php if($_SESSION['proTip'] ?? ''){ ?>
        <div class="mb-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block mb-2" fill="rgb(253,224,71)" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            <span class="text-sm italic">Pro Tip: You can click on the status badge to quickly change it!</span>
        </div>
    <?php } $_SESSION['proTip'] = false; ?>
    <div class="flex flex-col vsm:mx-4 sm:mx-0">
        <div class="-my-2 overflow-visible sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="overflow-visible border-b border-gray-200 vsm:rounded-md sm:rounded-lg shadow-[0_0_11px_1px_rgba(0,0,0,0.11)] <?php if(!$moreThanFive) echo 'mb-10 sm:mb-0'; ?>">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="relative px-6 py-3 hidden sm:table-cell">
                                    <input id="master-checker" name="master-checker" type="checkbox" class="focus:ring-sky-500 h-4 w-4 text-sky-600 border-gray-300 rounded" disabled>
                                </th>
                                <th scope="col" class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider max-w-[100px] vsm:rounded-tl-lg sm:rounded-none">
                                    Title
                                </th>
                                <th scope="col" class="lg:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider hidden sm:table-cell">
                                    Created
                                </th>
                                <th scope="col" class="lg:px-6 py-3 text-center w-24 text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Status
                                </th>
                                <th scope="col" class="lg:px-6 py-3 text-left w-[4.5rem] text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Actions
                                </th>
                            </tr>
                        </thead>

                        <tbody class="bg-white divide-y divide-gray-200">
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap hidden sm:table-cell">
                                        <input id="" name="status-checker" type="checkbox" class="focus:ring-sky-500 h-4 w-4 text-sky-600 border-gray-300 rounded" disabled>
                                    </td>
                                    <td class="px-2 py-4 whitespace-nowrap sm:rounded-none">
                                        <div class="flex items-center">
                                            <div class="resizer relative vsm:w-[350px] sm:w-[150px] w-[9rem] md:max-w-none <?php echo ($reqFrom) ? 'md:w-[300px]' : 'md:w-[200px]'; ?> lg:w-[400px] ">
                                                <div id="title" class="title-wrap text-left text-sm font-medium truncate hover:absolute hover:top-[-12px] hover:rounded-[1px] hover:shadow-[0_0_4px_0_black] hover:bg-white hover:z-50 hover:whitespace-normal"></div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="lg:px-6 py-4 whitespace-nowrap text-left hidden sm:table-cell">
                                        <div class="text-sm text-gray-900">
                                            <span class="text-sm block text-gray-500" id="created"></span>
                                        </div>
                                    </td>
                                    <td class="lg:px-6 py-4 whitespace-nowrap text-center">
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full" id="status"></span>
                                    </td>
                                    <td class="lg:px-6 py-4 whitespace-nowrap">
                                        <div class="relative flex items-center">
                                            <a href="<?php echo WEB_ROOT . '/todo/edit/'; ?>" id="edit">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                                </svg>
                                            </a>
                                            <a href="<?php echo '?delete='; ?>" id="remove">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                </svg>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                        </tbody>
                    </table>
                </div>
                <?php if($moreThanFive){ ?>
                    <div class="text-right animate-pulse text-sm mt-1 mb-10 sm:mb-0">
                        <a class="text-slate-400" href="<?php echo WEB_ROOT . '/todo/list'; ?>">See the full list</a>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php if($reqFrom) echo "</div>"; ?>

    <script id="todosRef"> todos = <?php echo json_encode( (!$reqFrom) ? array_slice($this->userTodos, -5, 5) : $this->userTodos); ?>; </script>

    <?php $this->appendScript('listHelpers.js'); ?>

    <script>
        // Render list
        init();
        document.querySelector('#todosRef').remove();
        delete todos;
        removeOverflowEffect();
    </script>

<?php } else {
    echo ($reqFrom) ? '<div class="text-2xl font-bold align-super mx-4 font-normal text-transparent 
                            bg-clip-text bg-gradient-to-r from-slate-400 to-gray-900">
                            Try to create some Todo to see it here!
                       </div>' : '';
} ?>

<?php
    if (isset($_GET['delete']) || isset($_GET['assign'])) {
        echo $this->_renderViewScript('global/modal.phtml', true);
    }
?>