<form method="POST">
    <?php
        echo $_SESSION['error'] ?? '';
        echo $_SESSION['info'] ?? '';
        unset($_SESSION['error'], $_SESSION['info']);
    ?>
    <input type="text" name="newTodo" placeholder="What do you have to do?" style="font-size: 2rem" class="mt-1 inline-block px-3 py-2 bg-white border border-slate-300 rounded-md text-sm placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none border-gray-500 shadow-lg shadow-cyan-500/50" autofocus >
    <button class="p-4 bg-cyan-500 shadow-lg rounded-lg hover:bg-cyan-600 text-gray-100 text-[2rem] hover:text-gray-300 ">Create!</button>
    <?php
        $reqFrom = $_SERVER['REQUEST_URI'] ?? '';
        $reqFrom = preg_match('/\/todo\/new/', $reqFrom);
        
        if($reqFrom == true){
            echo $_SESSION['success'] ?? '';
        }
        
        unset($_SESSION['success']);
    ?>
</form>