<form method="POST">
    <?php
        echo $_SESSION['error'] ?? '';
        echo $_SESSION['info'] ?? '';
        unset($_SESSION['error'], $_SESSION['info']);

        $reqFrom = $_SERVER['REQUEST_URI'] ?? '';
        $reqFrom = preg_match('/\/todo\/new/', $reqFrom);
        
        if($reqFrom == true){
            echo $_SESSION['success'] ?? '';
        }
        
        unset($_SESSION['success']);
    ?>
    <input type="text" name="newTodo" placeholder="What do you have to do?" style="font-size: 2rem" autofocus>
    <button style="font-size: 2rem; color: grey">Submit</button>
</form>