<!-- Content from index#index -->
<div class="error-msg" style="background: green"><?php echo (isset($_SESSION['assignedSuccess']) && $_SESSION['assignedSuccess'] === true) ? 'Todo\'s cretead while you were not authenticated had been successfully added to this account!' : null; unset($_SESSION['assignedSuccess']); ?></div>
<div style="position: relative; text-align: center">
    <?php echo $this->_renderViewScript('todo/new.phtml', true); ?><br>
    <?php echo $this->_renderViewScript('todo/list.phtml', true); ?><br>
</div>