<div class="relative text-center vsm:w-full sm:w-fit">
    <?php 
        $assignSuccess = isset($_SESSION['assignedSuccess']) && $_SESSION['assignedSuccess'] === true;
        $fromRegister = preg_match('/register/', $_SERVER['HTTP_REFERER'] ?? '');

        if ($assignSuccess && !$fromRegister){ 
            echo $_SESSION['success'] ?? '';
            unset($_SESSION['success'], $_SESSION['assignedSuccess']); 
        }
    ?>
    <?php echo $this->_renderViewScript('todo/new.phtml', true); ?>
    <?php echo $this->_renderViewScript('todo/list.phtml', true); ?><br>
</div>