<div class="overflow-hidden sm:rounded-md shadow-[0_0_21px_1px_rgba(0,0,0,0.11)] border-2 border-slate-200">
    <div class="px-4 py-5 bg-white sm:p-6 flex">
        <div class="h-full bg-slate-50 border-slate-200 border-2 shadow-lg self-center p-2 rounded-full">
            <img src="<?php echo $this->user['avatarUrl'] ?? WEB_ROOT . '/img/no-avatar.png'; ?>" alt="" width="300" class="rounded-full">
        </div>
        <form method="POST">
            <div class="mt-2 ml-7">
                <?php
                    echo $_SESSION['success'] ?? '';
                    echo $_SESSION['error'] ?? '';
        
                    unset($_SESSION['success'], $_SESSION['error']);
                ?>
                <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
                <input type="text" value="<?php echo $this->user['username']; ?>" disabled class="appearance-none disabled:bg-gray-300 disabled:text-gray-500 relative block w-full px-3 py-2 border border-gray-400 placeholder-gray-500 text-gray-900 rounded-md sm:text-sm">
                <small>You created this account on 
                    <span class="font-medium"><?php echo date('l, F jS \of Y', strtotime($this->user['registerDate'])); ?> </span>
                </small>
                <!-- Password -->
                <label for="password" class="block text-sm font-medium text-gray-700 mb-1">Password</label>
                <button id="changePasswordBtn" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500 sm:mt-0  sm:w-auto sm:text-sm mb-2">
                    Change password
			    </button>
                <!-- Hidden by default -->
                <div id="trickster" class="transition-[height] duration-300 ease-linear">
                    <div id="passwordChanger" class="hidden animate-[fade_0.5s_ease-in-out]">
                        <input type="password" name="password" placeholder="Old Password" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm mb-2">
                        <input type="password" name="newPassword" placeholder="New Password" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm mb-2">
                        <input type="password" name="confirmPassword" placeholder="Confirm New Password" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm mb-2">
                    </div>
                </div>
                <!-- Email -->
                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                <input type="text" name="email" value="<?php echo $this->user['email']; ?>" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm mb-2">
                <!-- Avatar -->
                <label for="avatar" class="block text-sm font-medium text-gray-700">Avatar URL</label>
                <input type="text" name="avatarUrl" value="<?php echo $this->user['avatarUrl'] ?? ''; ?>" placeholder="Avatar URL" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm mb-2">
                <!-- Created Todos -->
                <span class="align-middle px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-sky-100 text-sky-800" id="status"><?php echo $this->user['createdTodos']; ?> Todos created</span>
                <!-- Form Buttons -->
                <div class="float-right">
                    <button id="reset" type="reset" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
                        Reset
                    </button>
                    <button type="submit" name="saveProfile" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 text-base font-medium text-white focus:outline-none focus:ring-2 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm bg-sky-600 hover:bg-sky-700 focus:ring-sky-500">
                        Save
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    const passwordChanger = document.querySelector('#passwordChanger');
    const trickster = document.querySelector('#trickster');

    document.querySelector('#changePasswordBtn').addEventListener('click', () => {
        trickster.style.height = trickster.offsetHeight + 'px';
        passwordChanger.classList.toggle('hidden');
        trickster.style.height = passwordChanger.offsetHeight + 'px';
    });
</script>