<form action="<?php echo WEB_ROOT . '/auth/login'; ?>" method="POST">
    <label for="username">Username:</label>
    <input type="text" name="username" required> <br>

    <label for="password">Password:</label>
    <input type="text" name="password" required> <br>

    <button type="submit">Login</button>
    <span style="font-size: 0.8rem">Don't have an account? <a href="<?php echo WEB_ROOT . '/auth/register'; ?>">Register!</a></span>
</form>