<form method="POST">
    <div class="max-w-md w-full space-y-8">
        <div>
            <div class="wrapper-logo rounded-full">
                <svg class="logo-checkmark z-20 h-20 w-14" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52" >
                    <circle class="logo-checkmark__circle" cx="26" cy="26" r="25" fill="none" />
                    <path class="logo-checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
                </svg>
            </div>
            <h2 class="mt-2 text-center text-3xl font-extrabold text-gray-900">Create your account</h2>
            <p class="mt-2 text-center text-sm text-gray-600">
                Or <a href="<?php echo WEB_ROOT . '/auth/login'; ?>" class="font-medium text-sky-600 hover:text-sky-500"> sign in if you already have one</a>
            </p>
        </div>
        
        <?php 
            echo $_SESSION['error'] ?? ''; 
            unset($_SESSION['error']); 
        ?>
        <div class="shadow-sm -space-y-px">
            <input type="text" placeholder="Username" name="username" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        
            <input type="password" placeholder="Password" name="password" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-none focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        
            <input type="text" placeholder="Email address" name="email" class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        </div>
        
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Sign up
        </button>
    </div>
</form>

<script type="text/javascript">
    const created = <?php echo json_encode($this->accountCreated);?>;
    const tempUser = <?php echo json_encode(isset($_SESSION['tempUser']));?>;
    const successMsg = <?php echo json_encode($_SESSION['success'] ?? '');?>;
    <?php unset($_SESSION['success']); ?>

    if(created){
        const form = document.querySelector('form');
        form.innerHTML = successMsg;

        setTimeout(() => {
            if(tempUser){
                window.location.href = <?php echo json_encode(WEB_ROOT . '/todo/assign');?>;
            } else {
                window.location.href = <?php echo json_encode(WEB_ROOT);?>;
            }
        }, 2000);
    }
</script>