<form action="<?php echo WEB_ROOT . '/auth/register'; ?>" method="POST">
    <div class="error-msg" style="background: red"><?php echo $this->registerError ?></div>
    <label for="username">Username:</label>
    <input type="text" minlength="3" name="username" required> <br>

    <label for="password">Password:</label>
    <input type="password" minlength="6" name="password" required> <br>

    <label for="email">Email:</label>
    <input type="text" name="email" required> <br>
    
    <button type="submit">Register</button>
    <span style="font-size: 0.8rem">Already have an account? <a href="<?php echo WEB_ROOT . '/auth/login'; ?>">Login!</a></span>
</form>