<form method="POST">
    <div class="max-w-md w-full space-y-8">
        <?php 
            echo $_SESSION['error'] ?? ''; 
            unset($_SESSION['error']); 
        ?>
        <div class="shadow-sm -space-y-px">
            <input type="text" placeholder="Username" minlength="3" name="username" required class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        
            <input type="password" placeholder="Password" minlength="6" name="password" required class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-none focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        
            <input type="text" placeholder="Email address"" name="email" required class="appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-sky-500 focus:border-sky-500 focus:z-10 sm:text-sm">
        </div>
        
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Sign up
        </button>
    </div>
</form>

<script type="text/javascript">
    const created = <?php echo json_encode($this->accountCreated);?>;
    const tempUser = <?php echo json_encode(isset($_SESSION['tempUser']));?>;
    const successMsg = <?php echo json_encode($_SESSION['success'] ?? '');?>;
    <?php unset($_SESSION['success']); ?>

    if(created){
        const form = document.querySelector('form');
        form.innerHTML = successMsg;

        setTimeout(() => {
            if(tempUser){
                window.location.href = <?php echo json_encode(WEB_ROOT . '/todo/assign');?>;
            } else {
                window.location.href = <?php echo json_encode(WEB_ROOT);?>;
            }
        }, 2000);
    }
</script>