<div class="text-9xl">
    
    <?php if(strpos($this->error, 'no route added') === 0){ 
        $this->setTitle('404 | ' . APP_TITLE); ?>

        <div class="flex vsm:mb-4 sm:mb-0">
            <div class="vsm:text-7xl sm:text-9xl sm:align-text-bottom self-center inline-block drop-shadow-lg 
                font-semibold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-blue-600">
                404
            </div>
            <img src="<?php echo WEB_ROOT . '/img/sad-cat.gif'; ?>" class="inline-block self-center w-[100px] vsm:w-[100px] sm:w-[200px]">
        </div>
        <small class="vsm:text-6xl sm:text-[80%] align-super font-semibold text-transparent bg-clip-text bg-gradient-to-r from-slate-400 to-gray-900 block -mt-5">
                Not found
        </small>

    <?php } else { 
        $this->setTitle('Error | ' . APP_TITLE); ?>

        <div class="vsm:text-6xl sm:text-9xl align-text-bottom text-center block drop-shadow-lg 
             font-semibold text-transparent bg-clip-text bg-gradient-to-r from-rose-500 to-red-700">
                Error
        </div>
        <div class="mx-5 vsm:text-4xl sm:text-5xl max-w-xl font-normal text-transparent bg-clip-text
             bg-gradient-to-r from-slate-400 to-gray-900 mt-4 break-all">
            <?php echo $this->error; ?>
        </div>

    <?php } ?>
</div>
