<?php 
    $assignEnabled = isset($_SESSION['allowAssign']) && $_SESSION['allowAssign'] === true;
    $isUser = isset($_SESSION['loggedUser']);
    $fromRegister = preg_match('/register/', $_SERVER['HTTP_REFERER'] ?? '')
?>
<header>
    <nav class="bg-gray-800 pl-4 pr-4 flex justify-between min-h-[88px] shadow-lg shadow-gray-500/50 z-0">
        <div class="flex justify-between self-center">
            
            <!-- Logo Block -->
            <a href="<?php echo WEB_ROOT ?>" class="main-logo text-white logo-text text-3xl text-transparent bg-clip-text bg-gradient-to-br from-slate-100 via-slate-300 to-slate-400 flex space-x-2" onmouseover="typeof classSet == 'undefined' ? (this.children[0].children[0].classList.add('hover-out'), classSet = true) : null">
                <!-- Icon -->
                <div class="wrapper-logo rounded-full">
                    <svg class="logo-checkmark z-20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52" >
                        <circle class="logo-checkmark__circle" cx="26" cy="26" r="25" fill="none" />
                        <path class="logo-checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
                    </svg>
                </div>
                <!-- App Title -->
                <span><?php echo APP_TITLE ?></span>
            </a>

            <div class="hidden sm:block sm:ml-6">
            <div class="flex space-x-4">
                <a href="<?php echo WEB_ROOT ?>" class="text-gray-300 px-3 py-2 rounded-md text-sm font-medium hover:bg-gray-700 hover:text-white" id="dashboard">Home</a>
                <a href="<?php echo WEB_ROOT . '/todo/new' ?>" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="new">New</a>
                <a href="<?php echo WEB_ROOT . '/todo/list' ?>" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="list">List</a>
                <?php echo ($assignEnabled && $isUser && !$fromRegister) ? "<a href=" . WEB_ROOT . '/todo/assign' . " class='text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium' id='assign'>Assign Todos</a>" : '' ?>
            </div>
          </div>
        </div>
        <div class="float-right self-center">

            <?php if(!isset($_SESSION['loggedUser'])){ ?>

                <a href="<?php echo WEB_ROOT . '/auth/login' ?>" class="whitespace-nowrap text-base font-medium text-gray-500 hover:text-white">
                Sign in
                </a>

                <a href="<?php echo WEB_ROOT . '/auth/register' ?>" class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-sky-600 hover:bg-sky-700 hover:shadow-sky-500/20 hover:shadow-lg ">
                    Sign up
                </a>

            <?php } else { ?>

                <!-- User Block -->
                <div class="ml-3 relative">
                    <!-- Todo New Button -->
                    <a href="<?php echo WEB_ROOT . '/todo/new'; ?>" class="text-gray-400 hover:text-white">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 self-center mr-3 inline-block align-baseline mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                        </svg>
                    </a>

                    <!-- User Avatar -->
                    <div id="profile-opener" class="inline-block">
                        <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white bg-[#d8d8d8] hover:ring-slate-600 hover:ring-2 hover:ring-offset-2 hover:ring-offset-gray-800">
                            <span class="sr-only">Open user menu</span>
                            <img class="h-10 w-10 rounded-full" src="<?php echo $_SESSION['loggedUser']['avatarUrl'] ?? WEB_ROOT . '/img/no-avatar.png'; ?>" alt="">
                        </button>
                    </div>

                    <!-- Avatar Dropdown - Profile & Sign Out -->
                    <div class="transition-all ease-in-out opacity-0 duration-[400ms] origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg shadow-gray-500/50 py-1 bg-white ring-1 ring-black ring-opacity-5 invisible focus:outline-none">
                        <a href="<?php echo WEB_ROOT . '/user/profile' ?>" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">User Profile</a>
                        <a href="<?php echo WEB_ROOT . '/auth/logout' ?>" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Sign out</a>
                    </div>
                </div>
            
                <?php echo $this->appendScript('userPopup.js'); ?>

            <?php } ?> 
        </div>
    </nav>
</header>
<script>var webRoot = <?php echo json_encode(WEB_ROOT) ?>; </script>
<?php echo $this->appendScript('breadcrumbs.js'); ?>
