<?php
	// Shorthand Declarations

	$type = $this->modal['type'];
	$isDelete = ($type === 'Delete') ? true : false;
	$title = $this->modal['title'];
	$content = $this->modal['content'];
	$id = $this->modal['id'] ?? '';
	$deleteSVG = 'M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z';
	$assignSVG = 'M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z';
	$deleteBtn = 'bg-red-600 hover:bg-red-700 focus:ring-red-500';
	$assignBtn = 'bg-sky-600 hover:bg-sky-700 focus:ring-sky-500';
	$assignPageTitle = 'Assign todo' . (count($_SESSION['tempUser'] ?? []) > 1 ? 's' : '');
	($isDelete) ? $this->setTitle('Delete Todo | ' . APP_TITLE) : $this->setTitle( $assignPageTitle . ' | ' . APP_TITLE);
?>

<div id="modal-bg" class="flex items-center bg-black/40 justify-center left-0 top-0 fixed w-full h-full z-50 animate-fade px-4">
	<div id="modal-bg-alt" class="fixed inset-0 bg-gray-500/40 animate-fade transition-opacity"></div>
	<div id="modal" class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl animate-smooth transition-all transform sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
		<div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
			<div class="sm:flex sm:items-start">
				<div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full <?php echo ($isDelete) ? 'bg-red-100' : 'bg-sky-100' ?> sm:mx-0 sm:h-10 sm:w-10">
					<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 <?php echo ($isDelete) ? 'text-red-600' : 'text-sky-600' ?>" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="<?php echo ($isDelete) ? $deleteSVG : $assignSVG; ?>" />
					</svg>
				</div>
				<div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
					<h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
						<?php echo $title; ?>
					</h3>
					<div class="mt-2">
						<p class="text-sm text-gray-500">
							<?php echo $content; ?>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
			<button type="submit" name="deleteTodoId" value="<?php echo $id; ?>" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 text-base font-medium text-white focus:outline-none focus:ring-2 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm <?php echo ($isDelete) ? $deleteBtn : $assignBtn; ?>">
				<?php echo $type; ?>
			</button>
			<button id="cancel" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
				Cancel
			</button>
		</div>
	</form>
	</div>
</div>

<?php $this->appendScript('modal.js'); ?>