<!DOCTYPE html>
<html lang="en" class="m-0 p-0 text-xl">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo $this->_pageTitle ?></title>
	<?php $this->appendCSS('tailwind.css'); ?>
	<?php $this->appendScript('detectMobile.js'); ?>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="icon" type="image/png" href="<?php echo WEB_ROOT . '/img/favicon.png'; ?>">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@749&display=swap" rel="stylesheet">
</head>
<body class="bg-[url('../img/bg.jpg')] bg-cover bg-fixed bg-norepeat">
	<?php echo $this->_renderViewScript('global/header.phtml', true); ?>
	<main class="flex h-[calc(100vh_-_128px)]">
    	<div class="container flex items-center flex-col m-auto justify-center py-8 max-w-none">
			<?php echo $this->content(); /* Outputs the current action layout */ ?> 
		</div>
		<?php $this->appendScript('main.js'); ?>
	</main>
	<?php echo $this->_renderViewScript('global/footer.phtml', true); ?>
</body>
</html>